export const ENABLE_LOADING = 'ENABLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';

export const FETCH_EPISODES = 'FETCH_EPISODES';
export const ON_EPISODES_RESPONSE = 'ON_EPISODES_RESPONSE';

export const FETCH_EPISODE_DETAILS = 'FETCH_EPISODE_DETAILS';
export const ON_EPISODE_DETAILS_RESPONSE = 'ON_EPISODE_DETAILS_RESPONSE';

export const FETCH_CHARACTER_DETAILS = 'FETCH_CHARACTER_DETAILS';
export const ON_CHARACTER_DETAILS_RESPONSE = 'ON_CHARACTER_DETAILS_RESPONSE';